name: tbshop
description: "TBShop is a cross-platform e-commerce application built using Flutter and Firebase. It integrates artificial intelligence features to enhance user experience and optimize sales revenue. The application leverages AI for personalized product recommendations, demand forecasting, and customer behavior analysis, ensuring a smart and intuitive shopping experience for users."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  bcrypt: ^1.1.3
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  firebase_auth: ^5.5.1
  intl_phone_number_input: ^0.7.4
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  uuid: ^4.5.1
  flutter_rating_bar: ^4.0.1
  ml_linalg: ^13.12.6
  qr_flutter: ^4.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/